# The IPv4 address to bind the TCP and/or HTTP server to.
#
# server_ip: '127.0.0.1'

# Whether or not to enable the TCP server.
#
# tcp_server_enabled: true

# The port to bind the TCP server to.
#
# tcp_server_port: 5100

# The port to bind the HTTP server to.
#
# http_server_port: 8100

# Whether or not to enable th HTTP server.
#
# http_server_enabled: true

cameras:
  - name: 'Front Door Camera'
    device_index: 0
    # Path to the ONNX model containing the detector.
    #
    # detector_path: ''

    # Set the exposure mode to either:
    #
    #   - 'none'
    #     The exposure mode is not modified at all.
    #
    #   - 'auto'
    #     The exposure mode is set to automatic.
    #
    #   - 'manual'
    #     The exposure mode is set to manual.
    #
    #   - 'gradient_maximization'
    #     The exposure mode is set to manual and modified to maximize the image gradient magnitude.
    #
    exposure_mode: 'gradient_maximization'

    # The quality-to-compression ratio when sending the frames over the network.
    #
    stream_quality: 0.5

    # Used for detection people in the video stream.
    #
    people_detection:
      # Whether or not to enable people detection.
      #
      enabled: false

    # Used for storing captured camera frames in a rolling file directory.
    #
    storage:
      # Whether or not this feature is enabled.
      #
      enabled: true

      # The directory to store the image frames in.
      #
      # directory: '.'

      # At what size to store the captured frames at.
      #
      # May either be null (meaning no resize) or a dictionary containing 'width' and 'height' values, such as:
      #   size:
      #     width: 640
      #     height: 480
      size: null

      # The quality at which to storage the camera frames (in terms of quality-to-compression ratio).
      #
      quality: 0.5

      # How many days to keep each camera frame.
      # Set it to -1.0 in order for the max time to be unlimited.
      #
      days: 7.0


landscape_ui:
  grid:
    rows: 2
    cols: 3
  camera_widgets:
    - label: 'Front Door Camera'
      sensor_id: 0
      row: 0
      col: 0
      row_span: 1
      col_span: 1
  microphone_widgets: []
  chart_widgets: []
