# The IPv4 address to bind the TCP and/or HTTP server to.
#
# server_ip: '127.0.0.1'

# Whether or not to enable the TCP server.
#
# tcp_server_enabled: true

# The port to bind the TCP server to.
#
# tcp_server_port: 5100

# The port to bind the HTTP server to.
#
# http_server_port: 8100

# Whether or not to enable th HTTP server.
#
# http_server_enabled: true

cameras:
  - name: 'Front Door Camera'
    device_index: 0
    # Path to the ONNX model containing the detector.
    #
    # detector_path: ''

    # The quality-to-compression ratio when sending the frames over the network.
    #
    stream_quality: 1.0

    # Used for detection people in the video stream.
    #
    people_detection:
      # Whether or not to enable people detection.
      #
      enabled: false

    # Used for discarding frames that may not be of interest to the rest of the system.
    # Frames that are discarded will neither get streamed or stored on disk.
    #
    frame_filter:
      # Whether or not to enable the filter (default is false).
      #
      enabled: true

      # The path of the ONNX model that performs the filtering.
      # This model should be a binary image classifier (one scalar output)
      #
      model_path: 'frame_filter.onnx'

      # The index of the output containing the filter output.
      #
      output_index: 0

      # Whether or not to apply the sigmoid function to the output of the model.
      #
      apply_sigmoid: true

      # Do not let the filter reject frames for this many seconds.
      # If this many seconds pass by without a frame passing the filter, then one is let through and the timer restarts.
      # The default is 900 seconds, which is 15 minutes.
      #
      max_time: 900.0

      # When the filter model is expecting a certain input size, this transform can be used to resize the image into a
      # shape that the model can work with.
      #
      resize_transform:
        width: 160
        height: 120

      # Wether or not the input to the frame filter should be converted to grayscale.
      #
      grayscale_transform: true

    # Used for storing captured camera frames in a rolling file directory.
    #
    storage:
      # Whether or not this feature is enabled.
      #
      enabled: true

      # The directory to store the image frames in.
      #
      # directory: '.'

      # At what size to store the captured frames at.
      #
      # May either be null (meaning no resize) or a dictionary containing 'width' and 'height' values, such as:
      #   size:
      #     width: 640
      #     height: 480
      size: null

      # The quality at which to storage the camera frames (in terms of quality-to-compression ratio).
      #
      quality: 0.5

      # How many days to keep each camera frame.
      # Set it to -1.0 in order for the max time to be unlimited.
      #
      days: 7.0

      # Maximum number of frames per second to put into storage.
      rate: 1.0


landscape_ui:
  grid:
    rows: 1
    cols: 1
  camera_widgets:
    - label: 'Front Door Camera'
      sensor_id: 0
      row: 0
      col: 0
      row_span: 1
      col_span: 1
  microphone_widgets: []
  chart_widgets: []
